#!/usr/bin/env node

var assert = require('chai').assert
var fs = require('fs')
var path = require('path')
var jsdrafter = require('./jsdrafter.js');

var fixtures = '../test/fixtures/'

var apibs = [];
fs.readdirSync(fixtures).forEach(function(file) {
    if (path.extname(file) === ".apib") {
        var p = path.basename(file, '.apib');
        try {
            if (fs.statSync(path.join(fixtures, p+".result.json")).isFile()) {
                apibs.push({apib:path.join(fixtures,file),
                            result:path.join(fixtures, p+".result.json")});
            } else {
                console.error("Found "+path.join(fixtures,file)+" but not result!");
            }
        }
        catch (err) {
            assert.fail(true, false, err);
        }
    }
});

apibs.forEach(function(t) {
    var data = fs.readFileSync(t.apib, 'utf8');
    var expect = JSON.parse(fs.readFileSync(t.result, 'utf8'));
    var drafterRes = jsdrafter.parseAPIBlueprint(data);
    var x = 0;

    assert.equal(drafterRes.err, 0, "Prase "+t.apib);
    var res = JSON.parse(drafterRes.result);
    assert.deepEqual(res, expect, "Parsed correctly as expected");
});

return 0;
