# Copyright 2018 Thomas Jandecka
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt

cmake_minimum_required(VERSION 3.5 FATAL_ERROR)

find_package(BoostIntrusive 1.66 REQUIRED)
find_package(BoostSmartPtr 1.66 REQUIRED)
find_package(BoostTuple 1.66 REQUIRED)

add_executable(boost_container_alloc_basic_test test/alloc_basic_test.cpp)
target_link_libraries(boost_container_alloc_basic_test PRIVATE Boost::container)
add_test(BoostContainer_alloc_basic_test boost_container_alloc_basic_test)

add_executable(boost_container_alloc_full_test test/alloc_full_test.cpp)
target_link_libraries(boost_container_alloc_full_test PRIVATE Boost::container)
add_test(BoostContainer_alloc_full_test boost_container_alloc_full_test)

add_executable(boost_container_allocator_traits_test test/allocator_traits_test.cpp)
target_link_libraries(boost_container_allocator_traits_test PRIVATE Boost::container)
add_test(BoostContainer_allocator_traits_test boost_container_allocator_traits_test)

add_executable(boost_container_deque_test test/deque_test.cpp)
target_link_libraries(boost_container_deque_test PRIVATE Boost::container Boost::intrusive_test)
add_test(BoostContainer_deque_test boost_container_deque_test)

add_executable(boost_container_explicit_inst_deque_test test/explicit_inst_deque_test.cpp)
target_link_libraries(boost_container_explicit_inst_deque_test PRIVATE Boost::container)
add_test(BoostContainer_explicit_inst_deque_test boost_container_explicit_inst_deque_test)

add_executable(boost_container_explicit_inst_flat_map_test test/explicit_inst_flat_map_test.cpp)
target_link_libraries(boost_container_explicit_inst_flat_map_test PRIVATE Boost::container Boost::intrusive_test)
add_test(BoostContainer_explicit_inst_flat_map_test boost_container_explicit_inst_flat_map_test)

add_executable(boost_container_explicit_inst_flat_set_test test/explicit_inst_flat_set_test.cpp)
target_link_libraries(boost_container_explicit_inst_flat_set_test PRIVATE Boost::container)
add_test(BoostContainer_explicit_inst_flat_set_test boost_container_explicit_inst_flat_set_test)

add_executable(boost_container_explicit_inst_list_test test/explicit_inst_list_test.cpp)
target_link_libraries(boost_container_explicit_inst_list_test PRIVATE Boost::container)
add_test(BoostContainer_explicit_inst_list_test boost_container_explicit_inst_list_test)

add_executable(boost_container_explicit_inst_map_test test/explicit_inst_map_test.cpp)
target_link_libraries(boost_container_explicit_inst_map_test PRIVATE Boost::container)
add_test(BoostContainer_explicit_inst_map_test boost_container_explicit_inst_map_test)

add_executable(boost_container_explicit_inst_set_test test/explicit_inst_set_test.cpp)
target_link_libraries(boost_container_explicit_inst_set_test PRIVATE Boost::container)
add_test(BoostContainer_explicit_inst_set_test boost_container_explicit_inst_set_test)

add_executable(boost_container_explicit_inst_slist_test test/explicit_inst_slist_test.cpp)
target_link_libraries(boost_container_explicit_inst_slist_test PRIVATE Boost::container)
add_test(BoostContainer_explicit_inst_slist_test boost_container_explicit_inst_slist_test)

add_executable(boost_container_explicit_inst_small_vector_test test/explicit_inst_small_vector_test.cpp)
target_link_libraries(boost_container_explicit_inst_small_vector_test PRIVATE Boost::container)
add_test(BoostContainer_explicit_inst_small_vector_test boost_container_explicit_inst_small_vector_test)

add_executable(boost_container_explicit_inst_stable_vector_test test/explicit_inst_stable_vector_test.cpp)
target_link_libraries(boost_container_explicit_inst_stable_vector_test PRIVATE Boost::container)
add_test(BoostContainer_explicit_inst_stable_vector_test boost_container_explicit_inst_stable_vector_test)

add_executable(boost_container_explicit_inst_static_vector_test test/explicit_inst_static_vector_test.cpp)
target_link_libraries(boost_container_explicit_inst_static_vector_test PRIVATE Boost::container Boost::intrusive_test)
add_test(BoostContainer_explicit_inst_static_vector_test boost_container_explicit_inst_static_vector_test)

add_executable(boost_container_explicit_inst_string_test test/explicit_inst_string_test.cpp)
target_link_libraries(boost_container_explicit_inst_string_test PRIVATE Boost::container)
add_test(BoostContainer_explicit_inst_string_test boost_container_explicit_inst_string_test)

add_executable(boost_container_explicit_inst_vector_test test/explicit_inst_vector_test.cpp)
target_link_libraries(boost_container_explicit_inst_vector_test PRIVATE Boost::container)
add_test(BoostContainer_explicit_inst_vector_test boost_container_explicit_inst_vector_test)

add_executable(boost_container_flat_map_test test/flat_map_test.cpp)
target_link_libraries(boost_container_flat_map_test PRIVATE Boost::container Boost::intrusive_test)
add_test(BoostContainer_flat_map_test boost_container_flat_map_test)

add_executable(boost_container_flat_set_test test/flat_set_test.cpp)
target_link_libraries(boost_container_flat_set_test PRIVATE Boost::container Boost::intrusive_test)
add_test(BoostContainer_flat_set_test boost_container_flat_set_test)

add_executable(boost_container_flat_tree_test test/flat_tree_test.cpp)
target_link_libraries(boost_container_flat_tree_test PRIVATE Boost::container)
add_test(BoostContainer_flat_tree_test boost_container_flat_tree_test)

add_executable(boost_container_global_resource_test test/global_resource_test.cpp)
target_link_libraries(boost_container_global_resource_test PRIVATE Boost::container)
add_test(BoostContainer_global_resource_test boost_container_global_resource_test)

add_executable(boost_container_insert_vs_emplace_test test/insert_vs_emplace_test.cpp)
target_link_libraries(boost_container_insert_vs_emplace_test PRIVATE Boost::container)
add_test(BoostContainer_insert_vs_emplace_test boost_container_insert_vs_emplace_test)

add_executable(boost_container_list_test test/list_test.cpp)
target_link_libraries(boost_container_list_test PRIVATE Boost::container Boost::intrusive_test)
add_test(BoostContainer_list_test boost_container_list_test)

add_executable(boost_container_map_test test/map_test.cpp)
target_link_libraries(boost_container_map_test PRIVATE Boost::container Boost::intrusive_test)
add_test(BoostContainer_map_test boost_container_map_test)

add_executable(boost_container_memory_resource_test test/memory_resource_test.cpp)
target_link_libraries(boost_container_memory_resource_test PRIVATE Boost::container)
add_test(BoostContainer_memory_resource_test boost_container_memory_resource_test)

add_executable(boost_container_monotonic_buffer_resource_test test/monotonic_buffer_resource_test.cpp)
target_link_libraries(boost_container_monotonic_buffer_resource_test PRIVATE Boost::container)
add_test(BoostContainer_monotonic_buffer_resource_test boost_container_monotonic_buffer_resource_test)

add_executable(boost_container_node_handle_test test/node_handle_test.cpp)
target_link_libraries(boost_container_node_handle_test PRIVATE Boost::container)
add_test(BoostContainer_node_handle_test boost_container_node_handle_test)

add_executable(boost_container_null_iterators_test test/null_iterators_test.cpp)
target_link_libraries(boost_container_null_iterators_test PRIVATE Boost::container)
add_test(BoostContainer_null_iterators_test boost_container_null_iterators_test)

add_executable(boost_container_pair_test test/pair_test.cpp)
target_link_libraries(boost_container_pair_test PRIVATE Boost::container Boost::tuple)
add_test(BoostContainer_pair_test boost_container_pair_test)

add_executable(boost_container_pmr_deque_test test/pmr_deque_test.cpp)
target_link_libraries(boost_container_pmr_deque_test PRIVATE Boost::container)
add_test(BoostContainer_pmr_deque_test boost_container_pmr_deque_test)

add_executable(boost_container_pmr_flat_map_test test/pmr_flat_map_test.cpp)
target_link_libraries(boost_container_pmr_flat_map_test PRIVATE Boost::container)
add_test(BoostContainer_pmr_flat_map_test boost_container_pmr_flat_map_test)

add_executable(boost_container_pmr_flat_set_test test/pmr_flat_set_test.cpp)
target_link_libraries(boost_container_pmr_flat_set_test PRIVATE Boost::container)
add_test(BoostContainer_pmr_flat_set_test boost_container_pmr_flat_set_test)

add_executable(boost_container_pmr_list_test test/pmr_list_test.cpp)
target_link_libraries(boost_container_pmr_list_test PRIVATE Boost::container)
add_test(BoostContainer_pmr_list_test boost_container_pmr_list_test)

add_executable(boost_container_pmr_map_test test/pmr_map_test.cpp)
target_link_libraries(boost_container_pmr_map_test PRIVATE Boost::container)
add_test(BoostContainer_pmr_map_test boost_container_pmr_map_test)

add_executable(boost_container_pmr_set_test test/pmr_set_test.cpp)
target_link_libraries(boost_container_pmr_set_test PRIVATE Boost::container)
add_test(BoostContainer_pmr_set_test boost_container_pmr_set_test)

add_executable(boost_container_pmr_slist_test test/pmr_slist_test.cpp)
target_link_libraries(boost_container_pmr_slist_test PRIVATE Boost::container Boost::intrusive_test)
add_test(BoostContainer_pmr_slist_test boost_container_pmr_slist_test)

add_executable(boost_container_pmr_small_vector_test test/pmr_small_vector_test.cpp)
target_link_libraries(boost_container_pmr_small_vector_test PRIVATE Boost::container)
add_test(BoostContainer_pmr_small_vector_test boost_container_pmr_small_vector_test)

add_executable(boost_container_pmr_stable_vector_test test/pmr_stable_vector_test.cpp)
target_link_libraries(boost_container_pmr_stable_vector_test PRIVATE Boost::container)
add_test(BoostContainer_pmr_stable_vector_test boost_container_pmr_stable_vector_test)

add_executable(boost_container_pmr_static_vector_test test/pmr_static_vector_test.cpp)
target_link_libraries(boost_container_pmr_static_vector_test PRIVATE Boost::container)
add_test(BoostContainer_pmr_static_vector_test boost_container_pmr_static_vector_test)

add_executable(boost_container_pmr_string_test test/pmr_string_test.cpp)
target_link_libraries(boost_container_pmr_string_test PRIVATE Boost::container)
add_test(BoostContainer_pmr_string_test boost_container_pmr_string_test)

add_executable(boost_container_pmr_vector_test test/pmr_vector_test.cpp)
target_link_libraries(boost_container_pmr_vector_test PRIVATE Boost::container)
add_test(BoostContainer_pmr_vector_test boost_container_pmr_vector_test)

add_executable(boost_container_polymorphic_allocator_test test/polymorphic_allocator_test.cpp)
target_link_libraries(boost_container_polymorphic_allocator_test PRIVATE Boost::container)
add_test(BoostContainer_polymorphic_allocator_test boost_container_polymorphic_allocator_test)

add_executable(boost_container_resource_adaptor_test test/resource_adaptor_test.cpp)
target_link_libraries(boost_container_resource_adaptor_test PRIVATE Boost::container)
add_test(BoostContainer_resource_adaptor_test boost_container_resource_adaptor_test)

add_executable(boost_container_scoped_allocator_adaptor_test test/scoped_allocator_adaptor_test.cpp)
target_link_libraries(boost_container_scoped_allocator_adaptor_test PRIVATE Boost::container Boost::tuple)
add_test(BoostContainer_scoped_allocator_adaptor_test boost_container_scoped_allocator_adaptor_test)

add_executable(boost_container_scoped_allocator_usage_test test/scoped_allocator_usage_test.cpp)
target_link_libraries(boost_container_scoped_allocator_usage_test PRIVATE Boost::container)
add_test(BoostContainer_scoped_allocator_usage_test boost_container_scoped_allocator_usage_test)

add_executable(boost_container_set_test test/set_test.cpp)
target_link_libraries(boost_container_set_test PRIVATE Boost::container Boost::intrusive_test)
add_test(BoostContainer_set_test boost_container_set_test)

add_executable(boost_container_slist_test test/slist_test.cpp)
target_link_libraries(boost_container_slist_test PRIVATE Boost::container Boost::intrusive_test)
add_test(BoostContainer_slist_test boost_container_slist_test)

add_executable(boost_container_small_vector_test test/small_vector_test.cpp)
target_link_libraries(boost_container_small_vector_test PRIVATE Boost::container Boost::intrusive_test)
add_test(BoostContainer_small_vector_test boost_container_small_vector_test)

add_executable(boost_container_stable_vector_test test/stable_vector_test.cpp)
target_link_libraries(boost_container_stable_vector_test PRIVATE Boost::container Boost::intrusive_test)
add_test(BoostContainer_stable_vector_test boost_container_stable_vector_test)

add_executable(boost_container_static_vector_test test/static_vector_test.cpp)
target_link_libraries(boost_container_static_vector_test PRIVATE Boost::container Boost::intrusive_test Boost::smart_ptr)
add_test(BoostContainer_static_vector_test boost_container_static_vector_test)

add_executable(boost_container_string_test test/string_test.cpp)
target_link_libraries(boost_container_string_test PRIVATE Boost::container Boost::intrusive_test)
add_test(BoostContainer_string_test boost_container_string_test)

add_executable(boost_container_string_view_compat_test test/string_view_compat_test.cpp)
target_link_libraries(boost_container_string_view_compat_test PRIVATE Boost::container)
add_test(BoostContainer_string_view_compat_test boost_container_string_view_compat_test)

add_executable(boost_container_synchronized_pool_resource_test test/synchronized_pool_resource_test.cpp)
target_link_libraries(boost_container_synchronized_pool_resource_test PRIVATE Boost::container)
add_test(BoostContainer_synchronized_pool_resource_test boost_container_synchronized_pool_resource_test)

add_executable(boost_container_throw_exception_test test/throw_exception_test.cpp)
target_link_libraries(boost_container_throw_exception_test PRIVATE Boost::container)
add_test(BoostContainer_throw_exception_test boost_container_throw_exception_test)

add_executable(boost_container_tree_test test/tree_test.cpp)
target_link_libraries(boost_container_tree_test PRIVATE Boost::container)
add_test(BoostContainer_tree_test boost_container_tree_test)

add_executable(boost_container_unsynchronized_pool_resource_test test/unsynchronized_pool_resource_test.cpp)
target_link_libraries(boost_container_unsynchronized_pool_resource_test PRIVATE Boost::container)
add_test(BoostContainer_unsynchronized_pool_resource_test boost_container_unsynchronized_pool_resource_test)

add_executable(boost_container_uses_allocator_test test/uses_allocator_test.cpp)
target_link_libraries(boost_container_uses_allocator_test PRIVATE Boost::container)
add_test(BoostContainer_uses_allocator_test boost_container_uses_allocator_test)

add_executable(boost_container_vector_test test/vector_test.cpp)
target_link_libraries(boost_container_vector_test PRIVATE Boost::container Boost::intrusive_test)
add_test(BoostContainer_vector_test boost_container_vector_test)
